antlr4-python3-runtime==4.9.3
asttokens==2.0.8
attrs==22.1.0
backcall==0.2.0
blis==0.7.9
catalogue==2.0.8
certifi @ file:///croot/certifi_1665076670883/work/certifi
charset-normalizer==2.1.1
click==7.1.2
confection==0.0.3
cycler==0.11.0
cymem==2.0.7
debugpy==1.6.3
decorator==5.1.1
en-core-web-sm @ file:///mnt/dolphinfs/hdd_pool/docker/user/hadoop-aipnlp/dongguanting/DPR-main/en_core_web_sm-3.0.0.tar.gz
entrypoints==0.4
executing==1.1.1
faiss-cpu==1.7.2

hydra-core==1.2.0
idna==3.4
importlib-resources==5.10.0
ipykernel==6.16.1
ipython==8.5.0
jedi==0.18.1
Jinja2==3.1.2
joblib==1.2.0
jsonlines==3.1.0
jupyter_client==7.4.3
jupyter_core==4.11.2
kiwisolver==1.4.4
langcodes==3.3.0
MarkupSafe==2.1.1
matplotlib==3.3.4
matplotlib-inline==0.1.6
murmurhash==1.0.9
nest-asyncio==1.5.6
nltk==3.7
numpy==1.19.2
omegaconf==2.2.3
packaging==21.3
parso==0.8.3
pathy==0.6.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.2.0
preshed==3.0.8
prompt-toolkit==3.0.31
protobuf==4.21.8
psutil==5.9.3
ptyprocess==0.7.0
pure-eval==0.2.2
pydantic==1.8.2
Pygments==2.13.0
pyparsing==3.0.9
python-dateutil==2.8.2
PyYAML==6.0
pyzmq==24.0.1
regex==2022.9.13
requests==2.28.1
sacremoses==0.0.53
six==1.16.0
smart-open==5.2.1
spacy==3.0.8
spacy-legacy==3.0.10
spacy-loggers==1.0.3
srsly==2.4.5
stack-data==0.5.1
tensorboardX==2.1
thinc==8.0.17
tokenizers==0.10.3
torch==1.12.1+cu116
torchaudio==0.12.1+cu116
torchvision==0.13.1+cu116
tornado==6.2
tqdm==4.58.0
traitlets==5.5.0
transformers==4.3.3
typer==0.3.2
typing_extensions==4.4.0
urllib3==1.26.12
wasabi==0.10.1
wcwidth==0.2.5
wget==3.2
zipp==3.10.0
